name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main  

permissions:
     contents: 'read'
     id-token: 'write'
jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2  # Authenticates to Google Cloud with the Workload Identity Federation.
      with:
        project_id: 'astral-archive-416420'  # Your Google Cloud project ID.
        workload_identity_provider: 'projects/572907231686/locations/global/workloadIdentityPools/github/providers/my-repo'

    - name: Upload to Google Cloud Storage
      run: |
        gsutil cp ./404.html gs://cloud-static-site/404.html
        gsutil cp ./main.css gs://cloud-static-site/main.css
        gsutil cp ./main.html gs://cloud-static-site/main.html
        gsutil cp ./main.js gs://cloud-static-site/main.js
      # This step uploads each of the specified files to the designated paths in your Google Cloud Storage bucket.
